### ISSUE TITLE
Isomorphes Routing/Rendering

### ISSUE THREAD

**Issue by lxfrdl** [ldegen/irma#10]
Es wäre wünschenswert, wenn irma isomorphes Routing/Rendering unterstützt.

**Comment by ldegen** [comment]
Translation of original comment: 

> It would be nice if irma could somehow support „isomorphic routing/rendering“

@lxfrdl I *do* remember that it was me that suggested that you should open this issue :-). Looking at it today, I would say this is a bit out of scope for IRMa. 
Quite on the contrary, I would prefer the scope to be come smaller and better defined. See #18 for more details on my plans on this.
Bottom line is: I don't want IRMa to become a framework. I want it to be like a set of small tools that work together nicely.
