### ISSUE TITLE
support node version 8.9.3

### ISSUE THREAD

**Issue by eauw** [ldegen/irma#14]
Currently npm install not working with node v8.9.3

**Comment by ldegen** [comment]
Could you be more specific? What exactly is the problem?
fyi, it *does* work with 10.5.0, which happens to be what I am running right now...

**Comment by ldegen** [comment]
oops, didn't mean to close the issue just yet. :-)

**Comment by ldegen** [comment]
Hm... never got any feedback on this one. Closing for now. Let me know, if the issue still exists.
