### ISSUE TITLE
Missing controll for 404s

### ISSUE THREAD

**Issue by lxfrdl** [ldegen/irma#19]
After a previous change the internal middlewares are registered AFTER the external plugins. This makes a problem, when i want to handle 404s by myself.
If I call for example "/de/foo" it tries to fetch a document from the index "de" with the id "foo". Currently it returns the 404 from the ElasticSeach response.
So it would be nice if I got the ability to register custom "notFoundHandlers" after the internal middlewares which also results in an Express.js next(), when the above call returns an error.

**Comment by ldegen** [comment]
merged.

**Comment by ldegen** [comment]
the config attribute was renamed to `postPlugins`, since it works just like the existing `plugins` but is executed *after* the built in handlers.

The changes will land in 0.23.0
